spring:
  datasource:
    username: rafa
    password: 970311Kl!
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://139.196.122.222:3306/bishe?useSSL=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver